### ISSUE TITLE
Feature request: USB-C

### ISSUE THREAD

**Issue by tkornack** [blackmagic-debug/blackmagic-hardware#1]
USB-C is the only port on my computer and blackmagic is the only hardware I use without USB-C. Ignore the differential pins and just change the connector (plus the two pulldown resistors necessary for orientation negotiation.)

**Comment by incyi** [comment]
I agree with this.

**Comment by rs-development** [comment]
I just added a new PR. https://github.com/blacksphere/blackmagic-hardware/pull/5 We are working on an updated BMP with USB-C.

Comment or like if you don't mind.

**Comment by esden** [comment]
Thank you @tkornack we have now added USB-C to the official Black Magic Probe V2.3 hardware. It is available from [1BitSquared USA](https://1bitsquared.com/products/black-magic-probe) and [1BitSquared Germany](https://1bitsquared.de/products/black-magic-probe). :)
