### ISSUE TITLE
Blackmagic mini 2.1C PCB Files

### ISSUE THREAD

**Issue by forthnutter** [blackmagic-debug/blackmagic-hardware#3]
I looked at downloaded files from this repo
found the PCB's don't look anything like BMPM 2.1c PCB.
Is there anywhere else I can download the BMPM 2.1C PCB files

**Comment by esden** [comment]
Sorry @ajsb85 but that is too open of a forum for that. People can DM me an nicely ask for the design files explaining what they want to do with them. The schematics are published for most of the designs on the website already: https://black-magic.org/hardware.html
